services:
  - type: web
    name: rssbridge
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - .render.yaml
    envVars:
      - key: TZ
        value: Asia/Tokyo
